import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';
import { getSession, useSession } from 'next-auth/client';
import { Session } from 'next-auth';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';

const Home = (): JSX.Element => {
	const [session] = useSession();
	if (!session) return <Login />;
	return (
		<div className='h-screen bg:gray-100 overflow-hidden'>
			<Head>
				<title>FB Clone</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main className='flex'>
				<Sidebar />
				<Feed />
			</main>
		</div>
	);
};
// export const getStaticProps: GetStaticProps = async (context) => {};

// export const getStaticPaths: GetStaticPaths = async () => {};

export const getServerSideProps: GetServerSideProps<{
	session: Session | null;
}> = async (context) => {
	return {
		props: {
			session: await getSession(context),
		},
	};
};

export default Home;
