import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';
import { GetServerSideProps } from 'next';
import { getSession, useSession } from 'next-auth/client';
import { Session } from 'next-auth';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { db } from '../firebase';

const Home = ({ posts }): JSX.Element => {
	const [session] = useSession();
	if (!session) return <Login />;
	return (
		<div className='h-screen bg-gray-100 overflow-hidden'>
			<Head>
				<title>FB Clone</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main className='flex'>
				<Sidebar />
				<Feed posts={posts} />
				<Widgets />
			</main>
		</div>
	);
};

const getServerSideProps: GetServerSideProps<{
	session: Session | null;
}> = async (context) => {
	const posts = await db
		.collection('posts')
		.orderBy('timestamp', 'desc')
		.get();

	const docs = posts.docs.map((post) => ({
		id: post.id,
		...post.data(),
		timestamp: null,
	}));

	return {
		props: {
			session: await getSession(context),
			posts: docs,
		},
	};
};
export { getServerSideProps };
export default Home;
